package by.vsdev.posterminal.demo.dto

import by.vsdev.posterminal.demo.model.CommandStatus
import by.vsdev.posterminal.demo.model.CommandType
import kotlinx.serialization.Serializable

/** Device registration. deviceId is generated on the device (stable id); token comes from a QR (optional). */
@Serializable
data class RegisterRequest(
    val deviceId: String,
    val name: String,
    val model: String? = null,
    val enrollmentToken: String? = null,
)

@Serializable
data class HeartbeatRequest(val timestamp: Long, val batteryLevel: Int? = null, val kioskActive: Boolean? = null)

/** Enqueue a new command (from the admin console). */
@Serializable
data class NewCommandRequest(val type: CommandType, val payload: String? = null)

/** Acknowledgement that the device executed the command. */
@Serializable
data class AckRequest(val status: CommandStatus = CommandStatus.DONE)

/** QR-enrollment token generated by the admin console. */
@Serializable
data class EnrollmentToken(val token: String, val serverUrl: String)
